blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()], )
    submit = SubmitField('Post')



blog/main/routes.py
from flask import Blueprint
from flask import render_template, request
from blog.main.utils import date_format

from blog.models import Post

main_bp = Blueprint('main_bp', __name__)


@main_bp.route("/")
@main_bp.route("/home")
def home():
    # return "<h2><font color='green'>Hello World !!!</font></h2>"
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template('index.html', posts=posts, title="Home", date_format=date_format)


@main_bp.route("/home/<username>")
def homeuser(username):
    # return "<h2><font color='green'>Hello World !!!</font></h2>"
    return render_template('index.html', username=username)


@main_bp.route("/about")
def about():
    return render_template('about.html', title="About")



@main_bp.route("/test")
def test():
    return """
        <head>
          <title>Test Page</title>
          <link href="../static/site.css" rel="stylesheet">
        </head>

        <body>

          <div id="main">
          <h1>Welcome to Test page</h1>
          <h2>The whole contents of this page are created using triple-quote string</h2>

          <p>Pages (HTML)</p>
          <p>Style Sheets (CSS)</p>
          <p>Computer Code (JavaScript)</p>
          <p>Live Data (Files and Databases)</p>
          </div>

        </body>
    """


blog/posts/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect,  abort #, make_response
from blog import db
from blog.posts.forms import PostForm
from blog.models import Post
from flask_login import  current_user, login_required
from blog.main.utils import date_format

posts_bp = Blueprint('posts_bp', __name__)


@posts_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(form.title.data, form.content.data, current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Your post is submitted', 'success')
        return redirect(url_for('main_bp.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='Update Post')


@posts_bp.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)

    return render_template('post.html', title=post.title, post = post, date_format=date_format)


@posts_bp.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    # Only the user who created the post can edit it
    if post.author != current_user:
        abort(403)

    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.contents = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts_bp.post', post_id=post.id))

    form.title.data = post.title
    form.content.data = post.contents
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()

    flash('Posted deleted successfully', 'success')
    return redirect(url_for('main_bp.home'))


blog/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request,session
from blog import  bcrypt, db
from blog.users.forms import LoginForm, RegistrationForm, UpdateAccountForm,  RequestResetForm, ResetPasswordForm
from blog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from blog.main.utils import save_picture, send_reset_email,date_format

users_bp = Blueprint('users_bp', __name__)

@users_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))

    form = RegistrationForm()
    print("Debug:", form.username.data)

    if form.validate_on_submit():

        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(form.username.data, form.email.data, hashed_pw)
        db.session.add(user)
        db.session.commit()

        flash(f'Account created for {form.username.data}! Pls login to continue.', 'success')

        return redirect(url_for('users_bp.login'))
    return render_template('register.html', title='Register', form=form)


@users_bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))

    form = LoginForm()

    if (form.validate_on_submit()):

            user = User.query.filter_by(email= form.email.data).first()

            if user and bcrypt.check_password_hash(user.password, form.password.data):
                session['power-by'] = 'DSRDSRDSR'
                login_user(user, remember=form.rememberme.data)

                redir_url = request.args.get('next')
                print('redir_url:', redir_url)
                return redirect(redir_url) if redir_url else redirect(url_for('main_bp.home'))

                # if form.email.data == 'admin@admin.com':
                #     flash('Login successful', 'success')
                #     return redirect(url_for('home'))

                # response = make_response( render_template('index.html', username= form.email.data) )
                # response.set_cookie('loggeduser', form.email.data)
                # return response
            else:
                flash('Login failed! Please check the email and password combination.', 'danger')
                # return abort(401)

    return render_template('login.html', title='Login', form=form)

@users_bp.route("/logout")
def logout():
    logout_user()
    session.clear()
    session.delete()
    return redirect(url_for('main_bp.home'))


@users_bp.route("/account",  methods=['GET', 'POST'])
@login_required
def account():
    # if not current_user.is_authenticated:
    #     flash('You need to be login first before you can see the Accounts section', 'danger')
    #     return redirect(url_for('login'))

    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_fn = save_picture(form.picture.data)
            current_user.image_file = picture_fn

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users_bp.account'))

    form.username.data = current_user.username
    form.email.data = current_user.email
    dp = url_for('static', filename = 'profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', dp_url = dp, form=form)


@users_bp.route("/user/posts/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(author=user)\
                        .order_by(Post.date_posted.desc())\
                        .paginate(page=page, per_page=5)

    return render_template('user_posts.html', posts=posts, title=username + "'s Post", date_format=date_format, user=user)


@users_bp.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)

        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users_bp.login'))



    return render_template('reset_request.html', title="Reset Password", form=form)


@users_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('The token is expired or invalid.', 'warning')
        return redirect(url_for('userbp.reset_request'))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()

        flash('Your password has been updated', 'success')
        return redirect(url_for('userbp.login'))

    return render_template('reset_token.html', title="Reset Password", form=form)


blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <CENTER><IMG SRC="{{ url_for('static', filename='cloud.png') }}" ALIGN="BOTTOM" width="100%" >  </CENTER>

    <HR>
    <H1>Sample Blog</H1>
    <br>
    <H3>Created using : Python 3.8, Flask 1.1.2</H3> <br>
    Send me mail at <a href="mailto:dsrawat@dsr.com">dsrawat@dsr.com</a>
    <hr/>
    <center><B><I>&copy; Rawat Softwares, 2020</I></B></center>

{% endblock %}

blog/templates/account.html
{% extends "layout.html" %}
{% block content %}


<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ dp_url }}" width="100px">

        <div>
            <div class="media-body ml-4">
                <p></p>
                <h2 class="account-heading text-primary"> {{ current_user.username }}</h2>
                <p class="text-secondary text-info"><b>{{ current_user.email }} </b></p>
            </div>
        </div>
    </div>

    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="bottom-border mb-4"><b>Account Info</b> </legend>
            <div class="form-group">
                {{ form.username.label(class = "form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span> {{error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class = "form-control-plaintext form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.email.label(class = "form-control-label") }}

                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span> {{error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class = "form-control-plaintext form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.picture.label }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger"> {{error }} </span><br>
                {% endfor %}
            {% endif %}
        </div>

         <div class="form-group">
                {{ form.submit(class = "btn btn-outline-info") }}
         </div>
    </form>
</div>


{% endblock %}

blog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="bottom-border mb-4"> {{ legend }}</legend>

            <div class="form-group">
                {{ form.title.label(class = "form-control-label") }}

                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span> {{error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class = "form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.content.label(class = "form-control-label") }}

                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid", rows=10) }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span> {{error }} </span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class = "form-control " , rows=10) }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class = "btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}

blog/templates/index.html
{% extends "layout.html" %}
{% block content %}
{% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">

    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users_bp.user_posts', username=post.author.username )}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ date_format(post.date_posted) }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts_bp.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.contents }}</p>
    </div>
</article>
{% endfor %}

{%  for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {%  if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4"    href="{{ url_for('main_bp.home', page=page_num)}}"> {{page_num}} </a>
        {% else %}
        <a class="btn btn-outline-info mb-4"    href="{{ url_for('main_bp.home', page=page_num)}}"> {{page_num}} </a>
        {% endif %}
    {%  else %}
    ...
    {%  endif %}
{%  endfor %}

{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--
    <link rel="stylesheet" href="../static/site.css" >      OR
    <link rel="stylesheet" href="{{ url_for('static', filename='site.css') }} " >
    -->

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <meta charset="UTF-8">
       <title>
    {% if title %}
        {{title}}
    {% else %}
        My Blog
    {% endif%}
    </title>

</head>
<body>

  <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main_bp.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main_bp.about') }}">About</a>
               {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts_bp.new_post') }}">New Post</a>
               {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users_bp.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users_bp.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users_bp.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users_bp.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
   <div class="content-section">
        <form method="POST" action="" >
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="bottom-border mb-4">Log In</legend>


                <div class="form-group">
                    {{ form.email.label(class = "form-control-label") }}

                     {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%  for error in form.email.errors %}
                                <span> {{error }} </span>
                            {%  endfor %}
                        </div>
                    {%  else %}
                        {{ form.email(class = "form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class = "form-control-label") }}

                     {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%  for error in form.password.errors %}
                                <span> {{error }} </span>
                            {%  endfor %}
                        </div>
                    {%  else %}
                        {{ form.password(class = "form-control form-control-lg") }}
                    {% endif %}

                </div>

                <divc class="form-check">
                    {{ form.rememberme(class="form-check-input") }}
                    {{ form.rememberme.label(class="form-check-label") }}
                </divc>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class = "btn btn-outline-info") }}
            </div>

        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted ml-2">
                <a href="{{ url_for('users_bp.reset_request') }}">Forget password? </a>
        </small>

        <small class="text-muted ml-5">No account yet?
            <a class="ml-2" href="{{ url_for('users_bp.register') }}">Sign up today! </a>
        </small>
    </div>


{% endblock content %}

blog/templates/login2.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title> Login Page </title>
<style>
Body {
  font-family: Calibri, Helvetica, sans-serif;
  background-color: pink;
}
button {
       background-color: #4CAF50;
       width: 100%;
        color: orange;
        padding: 15px;
        margin: 10px 0px;
        border: none;
        cursor: pointer;
         }
 form {
        border: 3px solid #f1f1f1;
    }
 input[type=text], input[type=password] {
        width: 100%;
        margin: 8px 0;
        padding: 12px 20px;
        display: inline-block;
        border: 2px solid green;
        box-sizing: border-box;
    }
 button:hover {
        opacity: 0.7;
    }
  .cancelbtn {
        width: auto;
        padding: 10px 18px;
        margin: 10px 5px;
    }


 .container {
        padding: 25px;
        background-color: lightblue;
    }
</style>
</head>
<body>
    <center> <h1>Login Form </h1> </center>
    <form>
        <div class="container">
            <label>Username : </label>
            <input type="text" placeholder="Enter Username" name="username" required>
            <label>Password : </label>
            <input type="password" placeholder="Enter Password" name="password" required>
            <button type="submit">Login</button>
            <input type="checkbox" checked="checked"> Remember me
            <button type="button" class="cancelbtn"> Cancel</button>
            Forgot <a href="#"> password? </a>
        </div>
    </form>
</body>
</html>

blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">

    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2">{{ post.author.username }}</a>
            <small class="text-muted">{{ date_format(post.date_posted) }}</small>
        </div>

        <!-- Button trigger modal -->
        <a class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('posts_bp.update_post', post_id=post.id)  }}">Update</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
            Delete Post
        </button>


        <h2><a class="article-title">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.contents }}</p>
    </div>
</article>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this post?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form method="post" action="{{ url_for('posts_bp.delete_post', post_id=post.id) }}">
                    <input type="submit" class="btn btn-danger" value="Delete"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" >
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="bottom-border mb-4">Join Today!</legend>

                <div class="form-group">
                    {{ form.username.label(class = "form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%  for error in form.username.errors %}
                                <span> {{error }} </span>
                            {%  endfor %}
                        </div>
                    {%  else %}
                        {{ form.username(class = "form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class = "form-control-label") }}

                     {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%  for error in form.email.errors %}
                                <span> {{error }} </span>
                            {%  endfor %}
                        </div>
                    {%  else %}
                        {{ form.email(class = "form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class = "form-control-label") }}

                     {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%  for error in form.password.errors %}
                                <span> {{error }} </span>
                            {%  endfor %}
                        </div>
                    {%  else %}
                        {{ form.password(class = "form-control form-control-lg") }}
                    {% endif %}

                </div>

                <div class="form-group">
                    {{ form.confirm_password.label(class = "form-control-label") }}

                     {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {%  for error in form.confirm_password.errors %}
                                <span> {{error }} </span>
                            {%  endfor %}
                        </div>
                    {%  else %}
                        {{ form.confirm_password(class = "form-control form-control-lg") }}
                    {% endif %}

                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class = "btn btn-outline-info") }}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">Already have an account?
            <a class="ml-2" href="{{ url_for('users_bp.login') }}">Sign In</a>
        </small>
    </div>

{% endblock content %}

blog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}

<h1 class="mb-3">Posts by {{user.username}} ({{ posts .total}} ) </h1>

{% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img"
         src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">

    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users_bp.user_posts', username=post.author.username )}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ date_format(post.date_posted) }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts_bp.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.contents }}</p>
    </div>
</article>
{% endfor %}

{%  for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {%  if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4"    href="{{ url_for('users_bp.user_posts', username=user.username, page=page_num)}}"> {{page_num}} </a>
        {% else %}
        <a class="btn btn-outline-info mb-4"    href="{{ url_for('users_bp.user_posts', username=user.username, page=page_num)}}"> {{page_num}} </a>
        {% endif %}
    {%  else %}
    ...
    {%  endif %}
{%  endfor %}

{% endblock %}